---
- name: Install Step CLI
  become: true
  tags:
    - step
    - step_cli
  block:
    - name: Collect Debian architecture
      command: dpkg --print-architecture
      register: deb_arch
      check_mode: false # Run in check-mode as well as normal mode
      changed_when: false # Doesn't actually change anything
    - name: Install
      apt:
        deb: "https://github.com/smallstep/cli/releases/latest/download/step-cli_{{ deb_arch.stdout }}.deb"
